package openvpn

import (
	"bytes"
	"encoding/base64"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"net"
	"strconv"
	"strings"
	"time"
)

const (
	ProtoUDP = "udp"
	ProtoTCP = "tcp"

	CipherAES128GCM        = "AES-128-GCM"
	CipherAES192GCM        = "AES-192-GCM"
	CipherAES256GCM        = "AES-256-GCM"
	CipherAESCBC           = "AES-CBC"
	CipherAES128CBC        = "AES-128-CBC"
	CipherAES192CBC        = "AES-192-CBC"
	CipherAES256CBC        = "AES-256-CBC"
	CipherChaCha20Poly1305 = "CHACHA20-POLY1305"
	AuthMD5                = "MD5"
	AuthSHA1               = "SHA1"
	AuthSHA256             = "SHA256"
	AuthSHA384             = "SHA384"
	AuthSHA512             = "SHA512"

	CompLzoYes = "yes"

	VerifyX509TypeName       = "name"
	VerifyX509TypeNamePrefix = "name-prefix"
	VerifyX509TypeSubject    = "subject"
)

// ClientConfig is the normalized subset generated by hwdsl2/openvpn-install.
type ClientConfig struct {
	RemoteHost string
	RemotePort uint16
	Proto      string
	Dev        string
	Cipher     string
	Auth       string
	CompLZO    string
	// Compress is the --compress value: "", "stub", "stub-v2", "lzo",
	// "lz4" or "lz4-v2". Mutually exclusive with CompLZO.
	Compress string
	// compressMode is the framing resolved from CompLZO/Compress in Prepare.
	compressMode compressionMode

	CA         []byte
	Cert       []byte
	Key        []byte
	TLSCrypt   []byte
	TLSAuth    []byte
	TLSCryptV2 []byte
	// KeyDirection is the --tls-auth / --key-direction value (default
	// KeyDirectionClient). Ignored unless TLSAuth is set.
	KeyDirection int

	Username string
	Password string

	// VerifyX509Name optionally pins the server certificate subject
	// (--verify-x509-name). Empty means only chain + ServerAuth EKU are
	// verified, matching OpenVPN's default behavior.
	VerifyX509Name     string
	VerifyX509NameType string

	PeerInfo map[string]string

	PingInterval time.Duration
	PingRestart  time.Duration

	TLSCryptKey []byte
	TLSAuthKey  []byte
	// TLSCryptV2Kc is the per-client tls-crypt key; TLSCryptV2WKc is the
	// opaque wrapped key sent to the server in the initial hard reset.
	TLSCryptV2Kc  []byte
	TLSCryptV2WKc []byte
}

// DataCipherKeyLength returns the key size for the configured data cipher.
func (c ClientConfig) DataCipherKeyLength() int {
	return cipherKeyLength(c.Cipher)
}

// cipherKeyLength returns the key size in bytes for a data cipher.
func cipherKeyLength(cipher string) int {
	switch cipher {
	case CipherAES256GCM, CipherAES256CBC, CipherChaCha20Poly1305:
		return 32
	case CipherAES192GCM, CipherAES192CBC:
		return 24
	default:
		return 16
	}
}

// isSupportedAuth reports whether the HMAC digest is one the data channel can
// use (for CBC ciphers; AEAD ignores it).
func isSupportedAuth(auth string) bool {
	switch auth {
	case AuthMD5, AuthSHA1, AuthSHA256, AuthSHA384, AuthSHA512:
		return true
	default:
		return false
	}
}

// isSupportedCipher reports whether the data cipher can be used by the data
// channel (covers both the configured cipher and one negotiated via NCP).
func isSupportedCipher(cipher string) bool {
	switch cipher {
	case CipherAES128GCM, CipherAES192GCM, CipherAES256GCM,
		CipherAES128CBC, CipherAES192CBC, CipherAES256CBC, CipherChaCha20Poly1305:
		return true
	default:
		return false
	}
}

func (c ClientConfig) RemoteAddress() string {
	return net.JoinHostPort(c.RemoteHost, strconv.Itoa(int(c.RemotePort)))
}

func normalizeProto(proto string) string {
	switch strings.ToLower(strings.TrimSpace(proto)) {
	case "":
		return ProtoUDP
	case "udp", "udp4":
		return ProtoUDP
	case "tcp", "tcp-client", "tcp4", "tcp4-client":
		return ProtoTCP
	default:
		return strings.ToLower(strings.TrimSpace(proto))
	}
}

func normalizeCipher(cipher string) string {
	switch strings.ToUpper(strings.TrimSpace(cipher)) {
	case "":
		return CipherAES128GCM
	case CipherAESCBC:
		return CipherAES128CBC
	default:
		return strings.ToUpper(strings.TrimSpace(cipher))
	}
}

func normalizeAuth(auth string) string {
	switch strings.ToUpper(strings.TrimSpace(auth)) {
	case "":
		return AuthSHA256
	case "SHA-1":
		return AuthSHA1
	default:
		return strings.ToUpper(strings.TrimSpace(auth))
	}
}

func normalizeCompLZO(compLZO string) string {
	switch strings.ToLower(strings.TrimSpace(compLZO)) {
	case "yes", "adaptive":
		return CompLzoYes
	default:
		return strings.ToLower(strings.TrimSpace(compLZO))
	}
}

// resolveCompressionMode maps the comp-lzo / compress options to the wire
// framing. comp-lzo (any value, including "no") uses the legacy v1 no-swap
// framing; --compress uses v1-swap, and its -v2 variants use the v2 escape
// framing. Returns an error if both options request different framings.
func resolveCompressionMode(compLZO, compress string) (compressionMode, error) {
	compress = strings.ToLower(strings.TrimSpace(compress))
	lzo := compLZO != ""
	switch compress {
	case "":
		if lzo {
			return compressLZO, nil
		}
		return compressNone, nil
	case "stub-v2", "lz4-v2":
		if lzo {
			return compressNone, errors.New("openvpn config cannot set both comp-lzo and compress")
		}
		return compressV2Stub, nil
	case "stub", "lzo", "lz4":
		if lzo {
			return compressNone, errors.New("openvpn config cannot set both comp-lzo and compress")
		}
		return compressV1Stub, nil
	default:
		return compressNone, fmt.Errorf("unsupported openvpn compress %q: expected stub, stub-v2, lzo, lz4 or lz4-v2", compress)
	}
}

func (c *ClientConfig) Prepare() error {
	if c == nil {
		return errors.New("nil openvpn client config")
	}
	c.RemoteHost = strings.TrimSpace(c.RemoteHost)
	c.Proto = normalizeProto(c.Proto)
	if c.Dev == "" {
		c.Dev = "tun"
	}
	c.Dev = strings.ToLower(strings.TrimSpace(c.Dev))
	c.Cipher = normalizeCipher(c.Cipher)
	c.Auth = normalizeAuth(c.Auth)
	c.CompLZO = normalizeCompLZO(c.CompLZO)
	mode, err := resolveCompressionMode(c.CompLZO, c.Compress)
	if err != nil {
		return err
	}
	c.compressMode = mode
	if err := c.ValidateInstallScriptSubset(); err != nil {
		return err
	}
	hasCrypt := len(bytes.TrimSpace(c.TLSCrypt)) > 0
	hasAuth := len(bytes.TrimSpace(c.TLSAuth)) > 0
	hasCryptV2 := len(bytes.TrimSpace(c.TLSCryptV2)) > 0
	if btoi(hasCrypt)+btoi(hasAuth)+btoi(hasCryptV2) > 1 {
		return errors.New("openvpn config can set only one of tls-crypt, tls-auth and tls-crypt-v2")
	}
	if hasCrypt {
		key, err := DecodeStaticKey(c.TLSCrypt)
		if err != nil {
			return fmt.Errorf("parse tls-crypt key: %w", err)
		}
		c.TLSCryptKey = key
	}
	if hasCryptV2 {
		kc, wkc, err := DecodeTLSCryptV2ClientKey(c.TLSCryptV2)
		if err != nil {
			return fmt.Errorf("parse tls-crypt-v2 client key: %w", err)
		}
		c.TLSCryptV2Kc = kc
		c.TLSCryptV2WKc = wkc
	}
	if hasAuth {
		key, err := DecodeStaticKey(c.TLSAuth)
		if err != nil {
			return fmt.Errorf("parse tls-auth key: %w", err)
		}
		c.TLSAuthKey = key
		if c.KeyDirection != KeyDirectionServer && c.KeyDirection != KeyDirectionClient && c.KeyDirection != KeyDirectionBidirectional {
			return fmt.Errorf("invalid openvpn key-direction %d: expected 0, 1 or -1", c.KeyDirection)
		}
	}
	if c.VerifyX509Name != "" {
		switch c.VerifyX509NameType {
		case "":
			c.VerifyX509NameType = VerifyX509TypeName
		case VerifyX509TypeName, VerifyX509TypeNamePrefix, VerifyX509TypeSubject:
		default:
			return fmt.Errorf("invalid verify-x509-name type %q: expected %q, %q or %q", c.VerifyX509NameType, VerifyX509TypeName, VerifyX509TypeNamePrefix, VerifyX509TypeSubject)
		}
	}
	return nil
}

func (c *ClientConfig) ValidateInstallScriptSubset() error {
	if c == nil {
		return errors.New("nil openvpn client config")
	}
	if c.RemoteHost == "" || c.RemotePort == 0 {
		return errors.New("openvpn config requires remote host and port")
	}
	if c.Dev != "tun" {
		return fmt.Errorf("unsupported openvpn dev %q: only dev tun is supported", c.Dev)
	}
	if c.Proto != ProtoUDP && c.Proto != ProtoTCP {
		return fmt.Errorf("unsupported openvpn proto %q: only udp and tcp are supported", c.Proto)
	}
	if !isSupportedCipher(c.Cipher) {
		return fmt.Errorf("unsupported openvpn cipher %q: only %s, %s, %s, %s, %s, %s and %s are supported", c.Cipher, CipherAES128GCM, CipherAES192GCM, CipherAES256GCM, CipherAES128CBC, CipherAES192CBC, CipherAES256CBC, CipherChaCha20Poly1305)
	}
	if c.Auth != AuthMD5 && c.Auth != AuthSHA1 && c.Auth != AuthSHA256 && c.Auth != AuthSHA384 && c.Auth != AuthSHA512 {
		return fmt.Errorf("unsupported openvpn auth %q: only %s, %s, %s, %s and %s are supported", c.Auth, AuthMD5, AuthSHA1, AuthSHA256, AuthSHA384, AuthSHA512)
	}
	for name, value := range map[string][]byte{
		"ca": c.CA,
	} {
		if len(bytes.TrimSpace(value)) == 0 {
			return fmt.Errorf("openvpn config requires inline <%s> block", name)
		}
	}
	if block, _ := pem.Decode(c.CA); block == nil {
		return errors.New("inline <ca> block is not PEM")
	}
	hasCert := len(bytes.TrimSpace(c.Cert)) > 0 || len(bytes.TrimSpace(c.Key)) > 0
	if hasCert {
		if len(bytes.TrimSpace(c.Cert)) == 0 || len(bytes.TrimSpace(c.Key)) == 0 {
			return errors.New("openvpn cert and key must both be set when using client certificate auth")
		}
		if block, _ := pem.Decode(c.Cert); block == nil {
			return errors.New("inline <cert> block is not PEM")
		}
		if block, _ := pem.Decode(c.Key); block == nil {
			return errors.New("inline <key> block is not PEM")
		}
	} else if strings.TrimSpace(c.Username) == "" {
		return errors.New("openvpn requires either cert+key or username (auth-user-pass)")
	}
	if c.PingInterval < 0 {
		return errors.New("openvpn ping interval must be positive")
	}
	if c.PingRestart < 0 {
		return errors.New("openvpn ping restart must be positive")
	}
	return nil
}

func btoi(b bool) int {
	if b {
		return 1
	}
	return 0
}

// DecodeTLSCryptV2ClientKey parses an "OpenVPN tls-crypt-v2 client key" PEM
// block into the per-client key Kc (256 bytes, used exactly like a tls-crypt
// static key) and the opaque wrapped key WKc that is relayed to the server.
func DecodeTLSCryptV2ClientKey(block []byte) (kc []byte, wkc []byte, err error) {
	var raw []byte
	if der, _ := pem.Decode(block); der != nil {
		raw = der.Bytes
	} else {
		// Fall back to decoding the base64 body directly.
		var b64 strings.Builder
		for _, line := range strings.Split(string(block), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "-----") {
				continue
			}
			b64.WriteString(line)
		}
		raw, err = base64.StdEncoding.DecodeString(b64.String())
		if err != nil {
			return nil, nil, fmt.Errorf("base64: %w", err)
		}
	}
	// Need Kc plus at least the 2-byte WKc length trailer.
	if len(raw) < staticKeySize+2 {
		return nil, nil, fmt.Errorf("tls-crypt-v2 client key too short: %d bytes", len(raw))
	}
	kc = cloneBytes(raw[:staticKeySize])
	wkc = cloneBytes(raw[staticKeySize:])
	// The last two bytes of WKc are its own length in network byte order.
	declared := int(wkc[len(wkc)-2])<<8 | int(wkc[len(wkc)-1])
	if declared != len(wkc) {
		return nil, nil, fmt.Errorf("tls-crypt-v2 wrapped key length mismatch: declared %d, got %d", declared, len(wkc))
	}
	return kc, wkc, nil
}

func DecodeStaticKey(block []byte) ([]byte, error) {
	var hexLines []string
	for _, raw := range strings.Split(string(block), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "-----BEGIN OpenVPN Static key") || strings.HasPrefix(line, "-----END OpenVPN Static key") {
			continue
		}
		hexLines = append(hexLines, line)
	}
	encoded := strings.Join(hexLines, "")
	key, err := hex.DecodeString(encoded)
	if err != nil {
		return nil, err
	}
	if len(key) != 256 {
		return nil, fmt.Errorf("invalid static key length %d, expected 256 bytes", len(key))
	}
	return key, nil
}
